//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureClean
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItems
    {
        public int CartItemID { get; set; }
        public int CartID { get; set; }
        public int ServiceID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Services Services { get; set; }
    }
}
