//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureClean
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemTypes()
        {
            this.OrderItemDetails = new HashSet<OrderItemDetails>();
        }
    
        public int ItemTypeID { get; set; }
        public string Name { get; set; }
        public string Material { get; set; }
        public string CareInstructions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemDetails> OrderItemDetails { get; set; }
    }
}
