//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureClean
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSupplies
    {
        public int SupplyID { get; set; }
        public int MaterialID { get; set; }
        public int SupplierID { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> SupplyDate { get; set; }
        public string InvoiceNumber { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
