//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureClean
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItems()
        {
            this.MaterialUsages = new HashSet<MaterialUsages>();
            this.OrderItemDetails = new HashSet<OrderItemDetails>();
        }
    
        public int OrderItemID { get; set; }
        public int OrderID { get; set; }
        public int ServiceID { get; set; }
        public int Quantity { get; set; }
        public decimal PriceAtOrder { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialUsages> MaterialUsages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemDetails> OrderItemDetails { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Services Services { get; set; }
    }
}
