//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureClean
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemDetails
    {
        public int DetailID { get; set; }
        public int OrderItemID { get; set; }
        public int ItemTypeID { get; set; }
        public string SpecialNotes { get; set; }
    
        public virtual ItemTypes ItemTypes { get; set; }
        public virtual OrderItems OrderItems { get; set; }
    }
}
